schedule:
    resource: "@ScheduleBundle/Controller/"
    type:     annotation
    prefix:   /

authentication:
    resource: "@AuthenticationBundle/Controller/"
    type:     annotation
    prefix:   /
