security:
    encoders:
       Tapalava\User\User: bcrypt

    role_hierarchy:
        ROLE_USER: ~
        ROLE_ADMIN:
            - ROLE_USER

    providers:
        passwordless:
            id: login_provider

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: passwordless
                csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - link_authenticator
            logout:       true
            anonymous:    true
            remember_me:
                secret: '%secret%'
                lifetime: 9072500 # 15 weeks in seconds
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
