services:
    user.repository:
        class: Tapalava\User\CassandraUserRepository
        arguments:
            - '@m6web_cassandra.client.tapalava'

    link_authenticator:
        class: InkApplications\Knock\LinkAuthenticator
        arguments:
            - "@router"
            - "@security.password_encoder"
            - "@user.repository"

    login_sender:
        class: Tapalava\AuthenticationBundle\LoginSender
        arguments:
            - "@mailer"
            - "@twig"

    knock.login:
        class: InkApplications\Knock\Login
        arguments:
            - "@user.repository"
            - "@security.password_encoder"
            - "@login_sender"

    user.command.install:
        class: Tapalava\AuthenticationBundle\Command\DatabaseInstallCommand
        properties:
            client: "@m6web_cassandra.client.tapalava"
        tags:
            - { name: console.command }

    user.command.drop:
        class: Tapalava\AuthenticationBundle\Command\DatabaseDropCommand
        properties:
            client: "@m6web_cassandra.client.tapalava"
        tags:
            - { name: console.command }

    user.fake_provider:
        class: Tapalava\User\FakeUserProvider
