services:
    schedule.repository:
        class: Tapalava\Schedule\FakeScheduleRepository

    event.repository:
        class: Tapalava\Event\FakeEventRepository

    format_content_type:
        class: Tapalava\ScheduleBundle\Response\FormatContentType
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }
