services:
    schedule.repository:
        class: Tapalava\Schedule\CassandraScheduleRepository
        arguments:
            - '@m6web_cassandra.client.tapalava'
            - '@schedule.date_transformer'

    schedule.form_transformer:
        class: Tapalava\Schedule\ScheduleFormTransformer

    schedule.date_transformer:
        class: Tapalava\Schedule\DateCollectionTransformer

    http.request_parser:
        class: Tapalava\Http\RequestParser

    event.repository:
        class: Tapalava\Event\FakeEventRepository

    event.form_transformer:
        class: Tapalava\Event\EventFormTransformer

    format_content_type:
        class: Tapalava\ScheduleBundle\Response\FormatContentType
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }

    schedule.command.install:
        class: Tapalava\ScheduleBundle\Command\DatabaseInstallCommand
        properties:
            client: "@m6web_cassandra.client.tapalava"
        tags:
            - { name: console.command }

    schedule.command.drop:
        class: Tapalava\ScheduleBundle\Command\DatabaseDropCommand
        properties:
            client: "@m6web_cassandra.client.tapalava"
        tags:
            - { name: console.command }
